apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: platform-require-resource-limits
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-requests-and-limits
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - platform
      validate:
        message: CPU and memory requests and limits are required.
        pattern:
          spec:
            containers:
              - resources:
                  requests:
                    cpu: "?*"
                    memory: "?*"
                  limits:
                    cpu: "?*"
                    memory: "?*"

