apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-platform.fullname" . }}-secret
  labels:
    {{- include "app-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "app-platform.databaseUrl" . | quote }}
{{- if not .Values.postgresql.auth.existingSecret }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
{{- end }}

